### PR TITLE
GUI v2 edits

### PR DESCRIPTION
**Pull request by josephMDev**
SUMMARY:
- updated GUI design using style_sheets.py (very similar to CSS in design, introduced new color palette + tabs to UI) 
- updated tab_edit_main.py file functions and layout (still a work in progress) 
- included new .ui file called tab_edit.ui (one can now switch between ARO and MCC tabs) 
- included windows power-shell script for automating conversion between .ui files and .py files (windows only, will include BASH script for linux soon)
- qset.jpg used for program icon

### CODE REVIEW

**Comment by SeanTedesco** [comment]
Hey Joseph! Thank you for working on this! Just a couple of things: 

1. In the folder _gui/_ , there are folder called _edits_v2/_, and _groundstation_pyqt/_. Do we need to include both of these? 

2. Could you include instructions on how to run the program? I would like to set it up on the QSET computer and it would be easier to only have to follow some instructions. 

3. For future expansion and readability, it would be good to include all your _create__ methods in a seperate file. You could even create its own class, and make a library to use it. 

Sean

**Comment by josephMDev** [comment]
Hi Sean,

Thank you for your review.

1. Regarding the first issue, I included both versions of the GUI because I was not sure which version best suited the requirements for the rest of the sub-teams. Since, I recently realized we can (in the worst case) revert to the older version, we can just include this most recent GUI folder/version.

2. I will attach some formal instructions shortly. For now all that is needed to run the GUI is the two python scripts and .jpg image included in this pull request. To execute, simply run "tab_edit_main.py".

3. I'm still updating the python file structure (work in progress), but I will update that in the coming weeks.

**Comment by SeanTedesco** [comment]
Okay, that all sounds good to me. Let's include all those changes in this same pull request.

**Comment by SeanTedesco** [comment]
Incredible work, Joseph! I had to make some small changes to the requirements file, but I got it running on my system and the GUI is really starting to take shape. This is good to be merged. 

For reference, all one has to do to launch the GUI is:
```
python3 -m venv gui-venv
pip install --upgrade pip
pip install -r requirements.txt
python gui/src/main.py
```

**Pull request merged**
